### PR TITLE
Fix incorrect interpretation of exit codes from `xdg-mime` on KDE systems

### LINKED ISSUE #39: Handling non-zero exit codes from `xdg-mime` incorrectly interprets absence of protocol as an error on KDE
### **Describe the bug:**

When using the package to register custom protocols on a system running KDE, an error is thrown if the protocol isn't already registered. This behaviour stems from the `xdg-mime` utility's `defapp_kde` function treating a query for a non-existent protocol as a failure, [thus returning an exit code of 4](https://cgit.freedesktop.org/xdg/xdg-utils/tree/scripts/xdg-mime.in#n461) ("The action failed"). This is then [interpreted by protocol-registry as an error condition](https://github.com/Shubham-Kumar-2000/protocol-registry/blob/main/src/linux/index.js#L21), even though this behaviour is expected and appropriate when checking for a non-existent protocol.

### **To Reproduce:**

1. Install and use the `protocol-registry` package in a Node.js application on a KDE-based system.
2. Try to register a custom protocol that isn't already registered on the system.
3. `protocol-registry` will throw an error, indicating that the `xdg-mime query default x-scheme-handler/{protocol}` command failed.

### **Expected behaviour:**

`protocol-registry` should handle the exit code 4 from `xdg-mime` as an indication that the protocol does not exist, rather than as an error. No error should be thrown when attempting to register a new protocol that does not already have a handler.

### PR DESCRIPTION
**Pull request by GodBleak**
# Description:

This pull request fixes the handling of `xdg-mime` exit codes so the package no longer incorrectly interprets exit code 4 as an error on KDE-based systems. The fix updates the code in the `checkifExists` function to check if the system is using KDE, and if so handles exit code 4 appropriately.

Fixes #39 

## Type of change:

-   [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

-   [X] My code follows the style guidelines of this project.
-   [x] I have performed a self-review of my own code.
-   [X] I have commented my code, particularly in hard-to-understand areas.
-   [X] My changes generate no new warnings.
-   [X] New and existing unit tests pass locally with my changes.

### CODE REVIEW

File: src/linux/index.js [hunk 1]
```diff
@@ -18,13 +18,21 @@ const checkifExists = async (protocol) => {
         { silent: true }
     );
 
-    if (res.code !== 0 || res.stderr) {
+    /* 
+        KDE returns exit code 4 if the protocol is not registered
+        see https://cgit.freedesktop.org/xdg/xdg-utils/tree/scripts/xdg-mime.in#n461
+    */
+    const isKDE = process.env.XDG_CURRENT_DESKTOP === "KDE";
+    const kdeNoProtoExitCode = 4;
```
Comment (Shubham-Kumar-2000) [inline src/linux/index.js:26]: Can we move these 2 to `config/constants.js` ?

File: src/linux/index.js [hunk 2]
```diff
@@ -18,13 +18,21 @@ const checkifExists = async (protocol) => {
...
+    */
+    const isKDE = process.env.XDG_CURRENT_DESKTOP === "KDE";
+    const kdeNoProtoExitCode = 4;
+
+    if((res.code === 0 && !res.stderr) || (isKDE && res.code === kdeNoProtoExitCode)) {
+        if (res.stdout && res.stdout.length > 0) {
+            return true;
+        }
+        return false;
+    } else {
```
Comment (Shubham-Kumar-2000) [inline src/linux/index.js:33]: Also can we reduce if else nesting?
Try to put them at a single level

**Review by Shubham-Kumar-2000 — CHANGES_REQUESTED** [review]

**Review by Shubham-Kumar-2000 — APPROVED** [review]
